# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-05 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['instname']},
        ),
        migrations.AlterModelOptions(
            name='licence',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['servicename']},
        ),
    ]
