# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-03 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authgroup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='authgrouppermissions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='authpermission',
            options={},
        ),
        migrations.AlterModelOptions(
            name='authuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='authusergroups',
            options={},
        ),
        migrations.AlterModelOptions(
            name='authuseruserpermissions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='djangoadminlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='djangocontenttype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='djangosession',
            options={},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={},
        ),
        migrations.AlterModelOptions(
            name='licence',
            options={},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
    ]
