# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-04 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uun', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('department', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
    ]
