# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-04 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0002_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='so', to='helios.People'),
        ),
    ]
