# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-05 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0005_auto_20170205_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licence',
            name='institution_id',
        ),
        migrations.AlterField(
            model_name='licence',
            name='service_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serv', to='helios.Service'),
        ),
    ]
